### ISSUE TITLE
PDF font missing

### ISSUE THREAD

**Issue by relikd** [yadox666/The-Hackers-Hardware-Toolkit#10]
I'm downloading just the PDF (macOS). At least one font is missinging resulting in a broken appearance. Used fonts should be included in the PDF. E.g.:

Additionally, make the QR code clickable or add the URL below. This will enable users to open the product page without relying on a second device.

![hht1](https://user-images.githubusercontent.com/1321720/64125196-87061280-cda9-11e9-9a2d-a16dc7d30fc6.png)
![hht2](https://user-images.githubusercontent.com/1321720/64125197-87061280-cda9-11e9-88ec-903f6a225907.png)

**Comment by yadox666** [comment]
The catalog has been edited in Microsoft Word and the preferences and settings used should have embedded all the fonts, but... it hasn't. I really don't know why. I have tried many different settings and word versions and not better result. About the ocr codes with hyperlinks, that's a good idea. As I have time enough I will update it.

**Comment by relikd** [comment]
Not sure if it helps, but do you know or had a look at LaTeX? Could be a nice and clean way to share the source of the PDF with the community. Should also handle font integration appropriately without much hassle. However, you would need to rebuild your whole workflow. (But could be optimized with latex commmand to generate the same page layout for all articles).

If I have a spare few hours I will try to build a template for you …

**Comment by yadox666** [comment]
Finally solved!
