### ISSUE TITLE
10% LAB401 discount not working

### ISSUE THREAD

**Issue by mbrpdr** [yadox666/The-Hackers-Hardware-Toolkit#7]

**Comment by yadox666** [comment]
will ask LAB401 if they want to continue with the offer! Keep connected!

**Comment by yadox666** [comment]
They responded that they will keep it, so just try again, please!

**Comment by mbrpdr** [comment]
Awesome! It’s working again!

**Comment by yadox666** [comment]
Nice. I close it.
