### ISSUE TITLE
Hydrabus

### ISSUE THREAD

**Issue by ghecko** [yadox666/The-Hackers-Hardware-Toolkit#8]
You should add hydrabus in the bus category, it is a better alternative to bus pirate, always maintained and open-source. 
It provides assisted discovery of on-chip debug interfaces (jtag, swd) like jtagulator and it is not expensive.
[Shop link](https://lab401.com/products/hydrabus?_pos=1&_sid=52b2921e0&_ss=r&variant=8651407458415) & [project link](https://hydrabus.com/)

**Comment by yadox666** [comment]
Yes, you are right. I thought I had inserted it this time, but I didn't at the end. I will include it in the bus category. It's included but only in NFC section. I like also JTAGULATOR but my policy is not to insert things that are complicated to buy at the moment.

**Comment by yadox666** [comment]
Finally I decided to include both, hydrabus and jtagulator that could be also bought in some stores. Thank you.
