### ISSUE TITLE
HydraBus (non-NFC) price is wrong

### ISSUE THREAD

**Issue by 0x4d4e** [yadox666/The-Hackers-Hardware-Toolkit#9]
Hi!

The PDF lists the HydraBus (p100 - w/out HydraNFC) as 175€, but this is the price for the whole bundle (correct on p68).

Should be 75€ for the HydraBus alone.

Thx for the awesome list!

**Comment by yadox666** [comment]
Will revise it. Thank you.

**Comment by yadox666** [comment]
Revised and corrected
